apiVersion: v1
kind: Pod
metadata:
  name: frr-nginx
  annotations:
  k8s.v1.cni.cncf.io/networks: '[{"name": "nginx-nad","ips": ["192.168.1.100/24"], "mac": "20:04:0f:f1:88:B4"}]'
spec:
  containers:
  - name: nginx
    image: docker-registry.upshift.redhat.com/cnf-gotests/cnf-gotests-client:v4.8
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command: ["/bin/sleep", "3650d"]
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_CHROOT
