apiVersion: v1
kind: Pod
metadata:
  name: frr-bgp
spec:
  nodeName: helix13.lab.eng.tlv2.redhat.com
  hostNetwork: true
  volumes:
    - name: frr-config
      configMap:
        name: frr-config
  containers:
  - name: frr-bgp-pod
    image: frrouting/frr
    volumeMounts:
    - mountPath: "/etc/frr"
      name: frr-config
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW","SYS_ADMIN"]
